ALTER TABLE iocs
ADD COLUMN IF NOT EXISTS country VARCHAR(120);

ALTER TABLE iocs
ADD COLUMN IF NOT EXISTS region VARCHAR(120);

ALTER TABLE iocs
ADD COLUMN IF NOT EXISTS city VARCHAR(120);

ALTER TABLE iocs
ADD COLUMN IF NOT EXISTS asn VARCHAR(40);

ALTER TABLE iocs
ADD COLUMN IF NOT EXISTS isp VARCHAR(255);

ALTER TABLE iocs
ADD COLUMN IF NOT EXISTS whois TEXT;

ALTER TABLE iocs
ADD COLUMN IF NOT EXISTS passive_dns JSONB;

ALTER TABLE iocs
ADD COLUMN IF NOT EXISTS mitre JSONB;

ALTER TABLE iocs
ADD COLUMN IF NOT EXISTS tlp VARCHAR(30);

ALTER TABLE iocs
ADD COLUMN IF NOT EXISTS confidence SMALLINT DEFAULT 50;
